# Generated by Django 5.0.6 on 2024-05-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('blog', '0006_alter_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
