# Generated by Django 5.0.6 on 2024-05-14 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_comment_created_date_alter_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmark',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 22, 51, 34, 188272)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 22, 51, 34, 188272)),
        ),
    ]
