# Generated by Django 4.2.12 on 2024-05-15 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0031_remove_bookmark_bookmark_remove_post_bookmarks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 15, 13, 10, 48, 977896)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 15, 13, 10, 48, 977896)
            ),
        ),
    ]
