# Generated by Django 4.2.12 on 2024-05-15 10:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0032_alter_comment_created_date_alter_post_published_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="like",
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 15, 13, 48, 58, 405653)
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 15, 13, 48, 58, 405653)
            ),
        ),
    ]
