# Generated by Django 5.0.6 on 2024-05-20 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_comment_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreply',
            old_name='message',
            new_name='reply_message',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 15, 51, 40, 343477)),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 15, 51, 40, 344117)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 15, 51, 40, 342972)),
        ),
    ]
