# Generated by Django 5.0.6 on 2024-08-06 08:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_alter_post_options_post_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 12, 26, 27, 483496)),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 12, 26, 27, 483496)),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 12, 26, 27, 482457)),
        ),
    ]
