# Generated by Django 5.0.6 on 2024-08-06 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_alter_comment_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 13, 56, 6, 355097)),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 13, 56, 6, 355097)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 13, 56, 6, 354065)),
        ),
    ]
