# Generated by Django 5.0.6 on 2024-08-11 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_comment_post_alter_comment_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 13, 11, 0, 522001)),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
